package com.scrapy.common;

public interface ResponseJsonProperties {

    String JSON_PROPERTY_NEWS_SEARCH_RESPONSE_TOTAL_HITS = "total_hits";

    String JSON_PROPERTY_NEWS_SEARCH_RESPONSE_REASON = "reason";

    String JSON_PROPERTY_NEWS_SEARCH_RESPONSE_RESULT = "result";
    String JSON_PROPERTY_NEWS_SEARCH_RESPONSE_RETURN_OBJECT = "returnObject";

    String JSON_PROPERTY_NEWS_SEARCH_RESPONSE_DOCUMENT = "documents";

    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_ACCESS_KEY = "access_key";

    // argument
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_ARGUMENT_PUBLISHED_AT = "published_at";

    // fields
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_NEWS_ID = "news_id";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_PUBLISHED_AT = "published_at";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_ENVELOPED_AT = "enveloped_at";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_SUBJECT_INFO = "subject_info";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_SUBJECT_INFO1 = "subject_info1";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_SUBJECT_INFO2 = "subject_info2";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_SUBJECT_INFO3 = "subject_info3";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_SUBJECT_INFO4 = "subject_info4";

    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_CATEGORY_INCIDENT = "category_incident";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_PROVIDER_NEWS_ID = "provider_news_id";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_PROVIDER_CODE = "provider_code";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_PROVIDER_LINK_PAGE = "provider_link_page";
    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_FIELDS_PRINTING_PAGE = "printing_page";

    String JSON_PROPERTY_NEWS_SEARCH_REQUEST_HILIGHT = "hilight";

}
